### ISSUE TITLE
CreateIdempotent does not contain opcode 1.

### ISSUE THREAD

**Issue by lithdew** [solana-program/token#2]
`getCreateAssociatedTokenIdempotentInstruction` does not specify any data. The data it should specify is Uint8Array.of(1).

**Comment by lorisleiva** [comment]
Hi Kenta, I'm a bit confused. Aside from the instruction discriminator (which is token into account in the generated code), the `CreateIdempotent` instruction of the Associated Token program doesn't seem to accept any additional data.

**Comment by lithdew** [comment]
Right - the instruction discriminator (1) in this case I believe does not get included into the instruction data. The instruction data for CreateIdempotent is undefined.

https://github.com/solana-program/token/blob/f4769061222e28387e0c7d42663fb85bb65b3b2b/clients/js/src/generated/instructions/createAssociatedTokenIdempotent.ts#L247

**Comment by lorisleiva** [comment]
Oh I see! Well spotted, I'll fix that today. 🫡

**Comment by lorisleiva** [comment]
This should be fixed in version `0.1.4`. 🙏
